/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AudioMenus: typeof import('./src/components/AudioMenus.vue')['default']
    Comtent: typeof import('./src/components/Content/Comtent.vue')['default']
    Header: typeof import('./src/components/header/Header.vue')['default']
    NAlert: typeof import('naive-ui')['NAlert']
    NButton: typeof import('naive-ui')['NButton']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NEmpty: typeof import('naive-ui')['NEmpty']
    NFlex: typeof import('naive-ui')['NFlex']
    NIcon: typeof import('naive-ui')['NIcon']
    NImage: typeof import('naive-ui')['NImage']
    NSlider: typeof import('naive-ui')['NSlider']
    PlayControl: typeof import('./src/components/footer/PlayControl.vue')['default']
    Progress: typeof import('./src/components/progress/Progress.vue')['default']
  }
}
